name: eBCSgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9
  - numpy
  - pandas
  - pyparsing
  - regex
  - requests
  - scipy
  - setuptools
  - sortedcontainers
  - sympy
  - python-libsbml
  - lark
  - lark-parser >=0.11.3
  - pip
  - pytest
  - pip:
    - pymodelchecking==1.3.3
