name: eBCSgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9
  - numpy
  - pandas
  - pyparsing
  - regex
  - requests
  - scipy
  - sortedcontainers
  - sympy
  - python-libsbml
  - lark
  - lark-parser
  - pytest
  - pymodelchecking
